### ISSUE TITLE
My first impression

### ISSUE THREAD

**Issue by muhammadiqbalid83** [ahmadrosid/TitleCrafters#1]
ada 3 problem yang saya alami mas sebagai user.

1. saya bingung kenapa harus memasukan open ai key?
2. saya bingung kegunaan temperature.
3. tidak ada deskripsi untuk frameworknya.

**Comment by ahmadrosid** [comment]
> 1. saya bingung kenapa harus memasukan open ai key?

Karena ini gratis kamu perlu daftar ke openai untuk dapeting apikey nya, kamu bisa daftar disini: https://platform.openai.com/

> 2. saya bingung kegunaan temperature.

Temperature itu settingan biar AI nya bisa lebih kreatif, kamu bisa ubah - ubah temperaturenya untuk mendapatkan hasil title yang cocok

> 3. tidak ada deskripsi untuk frameworknya.

Iya nanti otw ditambahkan deskripsinya.
